//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ____Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelGuest
    {
        public int GuestID { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Roomname { get; set; }
        public System.DateTime CheckIN { get; set; }
        public System.DateTime CheckOUT { get; set; }
        public int Total { get; set; }
    }
}
