//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ____Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelRoom
    {
        public int roomID { get; set; }
        public string Roomname { get; set; }
        public int Price { get; set; }
    }
}
